export const ADD_NAME: "ADD_NAME";
export const ADD_POINT: "ADD_POINT";
export const CANVAS_HEIGHT: 200;
export const CANVAS_WIDTH: 320;
export const CONNECT: "CONNECT";
export const DISCONNECT: "DISCONNECT";
export const ERROR: "Game not properly initialised!";
export const MAXIMUM_GAME_SIZE: 4;
export const REMOVE_USER: "REMOVE_USER";
export const SELECT_MODE: "SELECT_MODE";
export const SOCKET_ADD_USER: "addUser";
export const SOCKET_CONNECT: "connect";
export const SOCKET_SELECT_MODE: "selectMode";
export const UPDATE_NAME: "UPDATE_NAME";
