export const ADD_NAME = 'ADD_NAME'
export const REMOVE_USER = 'REMOVE_USER'
export const SELECT_MODE = 'SELECT_MODE'
export const SOCKET_ADD_USER = 'addUser'
export const SOCKET_SELECT_MODE = 'selectMode'
export const UPDATE_NAME = 'UPDATE_NAME'
